general {
    disable_loading_bar = false
    hide_cursor         = true
    grace               = 0
}

background {
    monitor     =
    path        = screenshot
    blur_passes = 3
    blur_size   = 7
    brightness  = 0.5
}

input-field {
    monitor           =
    size              = 240, 48
    outline_thickness = 2
    dots_center       = true
    outer_color       = rgba(cba6f7ff)
    inner_color       = rgba(1e1e2edd)
    font_color        = rgba(cdd6f4ff)
    placeholder_text  = <i>Password...</i>
    position          = 0, -80
    halign            = center
    valign            = center
}

label {
    monitor     =
    text        = cmd[update:1000] echo "$(date +"%H:%M")"
    color       = rgba(cdd6f4ff)
    font_size   = 64
    font_family = JetBrainsMono Nerd Font
    position    = 0, 160
    halign      = center
    valign      = center
}

label {
    monitor     =
    text        = cmd[update:60000] echo "$(date +"%A, %d %B %Y")"
    color       = rgba(a6adc8ff)
    font_size   = 18
    font_family = Inter
    position    = 0, 80
    halign      = center
    valign      = center
}
