"$schema" = 'https://starship.rs/config-schema.json'
palette = "noctalia"

format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[bun]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'













# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (predefined colorscheme)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue      = "#b4bcc4"
red       = "#cdacac"
green     = "#b8c4b8"
yellow    = "#d4ccb4"
cyan      = "#b4c0c8"
magenta   = "#c0b8bc"
white     = "#e0dcd4"
black     = "#1a1d21"

# Extended palette (Catppuccin-compatible names)
rosewater = "#ccc4b4"
flamingo  = "#c8beb8"
pink      = "#c4beb8"
mauve     = "#c0b8bc"
maroon    = "#c8beb8"
peach     = "#ccc4b4"
teal      = "#b4c0c8"
sky       = "#b4c4bc"
sapphire  = "#b4bcc4"
lavender  = "#c4beb8"

# Text shades
text      = "#f0efeb"
subtext1  = "#e0dcd4"
subtext0  = "#515761"

# Surface shades
overlay2  = "#515761"
overlay1  = "#515761"
overlay0  = "#1a1d21"
surface2  = "#1a1d21"
surface1  = "#1a1d21"
surface0  = "#1a1d21"
base      = "#1a1d21"
mantle    = "#1a1d21"
crust     = "#1a1d21"
# <<< NOCTALIA STARSHIP PALETTE <<<
