color0 #1a1d21
color1 #cdacac
color2 #b8c4b8
color3 #d4ccb4
color4 #b4bcc4
color5 #c0b8bc
color6 #b4c0c8
color7 #e0dcd4
color8 #515761
color9 #c8beb8
color10 #b4beb4
color11 #ccc4b4
color12 #b4bcc4
color13 #c4beb8
color14 #b4c4bc
color15 #f0efeb
background #1a1d21
selection_foreground #f0efeb
cursor #d4ccb4
cursor_text_color #1a1d21
foreground #f0efeb
selection_background #3d424a
active_border_color #b4bcc4
inactive_border_color #b4bcc4

active_tab_foreground   #1a1d21
active_tab_background   #b4bcc4
inactive_tab_foreground #e0dcd4
inactive_tab_background #22262b
cursor_trail_color      #e0dcd4
