[config]

[templates]

[templates.hyprland-border]
input_path = "~/.config/noctalia/templates/hyprland-border.lua"
output_path = "~/.config/hypr/noctalia/border-colors.lua"
post_hook = "hyprctl reload"

