-- Generated by Noctalia user-template — do not edit directly.
-- Sets active border to Compline steel (#515761) independently of mPrimary.
local active   = "rgb(515761)"
local inactive = "rgb(22262b)"

hl.config({
    general = {
        col = {
            active_border   = active,
            inactive_border = inactive,
        },
    },
    group = {
        col = {
            border_active          = active,
            border_inactive        = inactive,
            border_locked_active   = active,
            border_locked_inactive = inactive,
        },
        groupbar = {
            col = {
                active          = active,
                inactive        = inactive,
                locked_active   = active,
                locked_inactive = inactive,
            },
        },
    },
})
