$primary = rgb(b4bcc4)
$surface = rgb(1a1d21)
$secondary = rgb(b4bcc4)
$error = rgb(cdacac)
$tertiary = rgb(b8c4b8)
$surface_lowest = rgb(1b1e23)
$active_border = rgb(515761)
$inactive_border = rgb(22262b)

general {
    col.active_border = $active_border
    col.inactive_border = $inactive_border
}

group {
    col.border_active = $active_border
    col.border_inactive = $inactive_border
    col.border_locked_active = $error
    col.border_locked_inactive = $inactive_border

    groupbar {
        col.active = $active_border
        col.inactive = $inactive_border
        col.locked_active = $error
        col.locked_inactive = $inactive_border
    }
}
